### ISSUE TITLE
Program should abort if a record cannot be inserted, not continue blindly

### ISSUE THREAD

**Issue by immesys** [SoftwareDefinedBuildings/sync2_quasar#1]
Right around here: https://github.com/SoftwareDefinedBuildings/sync2_quasar/blob/master/sync2_quasar/sync2_quasar.go#L287

You should break out the loop if success is false

**Comment by samkumar** [comment]
Fixed in commit 89d7be2cbe6a02cbcf3f629ec0de2d9c438d6ce6.
